// Notice: countries is only the file name and for convenience.
// This list consists of countries, regions, special administrative regions and disputed area.

export default {
    __: ["Unkown", "未知"],
    AF: ["Afghanistan", "阿富汗"],
    AX: ["Aland Island", "奥兰群岛"],
    AL: ["Albania", "阿尔巴尼亚"],
    DZ: ["Algeria", "阿尔及利亚"],
    AS: ["American Samoa", "美属萨摩亚"],
    AD: ["Andorra", "安道尔"],
    AO: ["Angola", "安哥拉"],
    AI: ["Anguilla", "安圭拉"],
    AQ: ["Antarctica", "南极洲"],
    AG: ["Antigua & Barbuda", "安提瓜和巴布达"],
    AR: ["Argentina", "阿根廷"],
    AM: ["Armenia", "亚美尼亚"],
    AW: ["Aruba", "阿鲁巴"],
    AU: ["Australia", "澳大利亚"],
    AT: ["Austria", "奥地利"],
    AZ: ["Azerbaijan", "阿塞拜疆"],
    BH: ["Bahrain", "巴林"],
    BD: ["Bangladesh", "孟加拉"],
    BB: ["Barbados", "巴巴多斯"],
    BY: ["Belarus", "白俄罗斯"],
    BE: ["Belgium", "比利时"],
    BZ: ["Belize", "伯利兹"],
    BJ: ["Benin", "贝宁"],
    BM: ["Bermuda", "百慕大"],
    BT: ["Bhutan", "不丹"],
    BO: ["Bolivia", "玻利维亚"],
    BA: ["Bosnia & Herzegovina", "波黑"],
    BW: ["Botswana", "博茨瓦纳"],
    BV: ["Bouvet Island", "布韦岛"],
    BR: ["Brazil", "巴西"],
    IO: ["British Indian Ocean Territory", "英属印度洋领地"],
    VG: ["British Virgin Islands", "英属维尔京群岛"],
    BN: ["Brunei", "文莱"],
    BG: ["Bulgaria", "保加利亚"],
    BF: ["Burkina", "布基纳法索"],
    BI: ["Burundi", "布隆迪"],
    KH: ["Cambodia", "柬埔寨"],
    CM: ["Cameroon", "喀麦隆"],
    CA: ["Canada", "加拿大"],
    CV: ["Cape Verde", "佛得角"],
    BQ: ["Caribbean Netherlands", "荷兰加勒比区"],
    KY: ["Cayman Islands", "开曼群岛"],
    CF: ["Central African Republic", "中非"],
    TD: ["Chad", "乍得"],
    CL: ["Chile", "智利"],
    CN: ["China", "中国"],
    CX: ["Christmas Island", "圣诞岛"],
    CC: ["Cocos (Keeling) Islands", "科科斯群岛"],
    CO: ["Colombia", "哥伦比亚"],
    CK: ["Cook Islands", "库克群岛"],
    CR: ["Costa Rica", "哥斯达黎加"],
    CI: ["Cote d'Ivoire", "科特迪瓦"],
    HR: ["Croatia", "克罗地亚"],
    CU: ["Cuba", "古巴"],
    CW: ["Curacao", "库拉索"],
    CY: ["Cyprus", "塞浦路斯"],
    CZ: ["Czech Republic", "捷克"],
    CD: ["Democratic Republic of the Congo", "刚果（金）"],
    DK: ["Denmark", "丹麦"],
    DJ: ["Djibouti", "吉布提"],
    DM: ["Dominica", "多米尼克"],
    DO: ["Dominican Republic", "多米尼加"],
    EC: ["Ecuador", "厄瓜多尔"],
    EG: ["Egypt", "埃及"],
    SV: ["El Salvador", "萨尔瓦多"],
    GQ: ["Equatorial Guinea", "赤道几内亚"],
    ER: ["Eritrea", "厄立特里亚"],
    EE: ["Estonia", "爱沙尼亚"],
    ET: ["Ethiopia", "埃塞俄比亚"],
    FK: ["Falkland Islands", "马尔维纳斯群岛（福克兰）"],
    FO: ["Faroe Islands", "法罗群岛"],
    FM: ["Federated States of Micronesia", "密克罗尼西亚联邦"],
    FJ: ["Fiji", "斐济群岛"],
    FI: ["Finland", "芬兰"],
    FR: ["France", "法国 法国"],
    GF: ["French Guiana", "法属圭亚那"],
    PF: ["French polynesia", "法属波利尼西亚"],
    TF: ["French Southern Territories", "法属南部领地"],
    GA: ["Gabon", "加蓬"],
    GM: ["Gambia", "冈比亚"],
    GE: ["Georgia", "格鲁吉亚"],
    DE: ["Germany", "德国"],
    GH: ["Ghana", "加纳"],
    GI: ["Gibraltar", "直布罗陀"],
    GB: ["United Kingdom", "英国"],
    GR: ["Greece", "希腊"],
    GL: ["Greenland", "格陵兰"],
    GD: ["Grenada", "格林纳达"],
    GP: ["Guadeloupe", "瓜德罗普"],
    GU: ["Guam", "关岛"],
    GT: ["Guatemala", "危地马拉"],
    GG: ["Guernsey", "根西岛"],
    GN: ["Guinea", "几内亚"],
    GW: ["Guinea-Bissau", "几内亚比绍"],
    GY: ["Guyana", "圭亚那"],
    HT: ["Haiti", "海地"],
    HM: ["Heard Island and McDonald Islands", "赫德岛和麦克唐纳群岛"],
    HN: ["Honduras", "洪都拉斯"],
    HK: ["Hong Kong (SAR)", "中国香港"],
    HU: ["Hungary", "匈牙利"],
    IS: ["Iceland", "冰岛"],
    IN: ["India", "印度"],
    ID: ["Indonesia", "印尼"],
    IR: ["Iran", "伊朗"],
    IQ: ["Iraq", "伊拉克"],
    IE: ["Ireland", "爱尔兰"],
    IM: ["Isle of Man", "马恩岛"],
    IL: ["Israel", "以色列"],
    IT: ["Italy", "意大利"],
    JM: ["Jamaica", "牙买加"],
    JP: ["Japan", "日本"],
    JE: ["Jersey", "泽西岛"],
    JO: ["Jordan", "约旦"],
    KZ: ["Kazakhstan", "哈萨克斯坦"],
    KE: ["Kenya", "肯尼亚"],
    KI: ["Kiribati", "基里巴斯"],
    KW: ["Kuwait", "科威特"],
    KG: ["Kyrgyzstan", "吉尔吉斯斯坦"],
    LA: ["Laos", "老挝"],
    LV: ["Latvia", "拉脱维亚"],
    LB: ["Lebanon", "黎巴嫩"],
    LS: ["Lesotho", "莱索托"],
    LR: ["Liberia", "利比里亚"],
    LY: ["Libya", "利比亚"],
    LI: ["Liechtenstein", "列支敦士登"],
    LT: ["Lithuania", "立陶宛"],
    LU: ["Luxembourg", "卢森堡"],
    MO: ["Macao (SAR)", "中国澳门"],
    MG: ["Madagascar", "马达加斯加"],
    MW: ["Malawi", "马拉维"],
    MY: ["Malaysia", "马来西亚"],
    MV: ["Maldives", "马尔代夫"],
    ML: ["Mali", "马里"],
    MT: ["Malta", "马耳他"],
    MH: ["Marshall Islands", "马绍尔群岛"],
    MQ: ["Martinique", "马提尼克"],
    MR: ["Mauritania", "毛里塔尼亚"],
    MU: ["Mauritius", "毛里求斯"],
    YT: ["Mayotte", "马约特"],
    MX: ["Mexico", "墨西哥"],
    MD: ["Moldova", "摩尔多瓦"],
    MC: ["Monaco", "摩纳哥"],
    MN: ["Mongolia", "蒙古国"],
    ME: ["Montenegro", "黑山"],
    MS: ["Montserrat", "蒙塞拉特岛"],
    MA: ["Morocco", "摩洛哥"],
    MZ: ["Mozambique", "莫桑比克"],
    MM: ["Myanmar (Burma)", "缅甸"],
    NA: ["Namibia", "纳米比亚"],
    NR: ["Nauru", "瑙鲁"],
    NP: ["Nepal", "尼泊尔"],
    NL: ["Netherlands", "荷兰"],
    NC: ["New Caledonia", "新喀里多尼亚"],
    NZ: ["New Zealand", "新西兰"],
    NI: ["Nicaragua", "尼加拉瓜"],
    NE: ["Niger", "尼日尔"],
    NG: ["Nigeria", "尼日利亚"],
    NU: ["Niue", "纽埃"],
    NF: ["Norfolk Island", "诺福克岛"],
    KP: ["North Korea", "朝鲜"],
    MP: ["Northern Mariana Islands", "北马里亚纳群岛"],
    NO: ["Norway", "挪威"],
    OM: ["Oman", "阿曼"],
    PK: ["Pakistan", "巴基斯坦"],
    PW: ["Palau", "帕劳"],
    PS: ["Palestinian territories", "巴勒斯坦"],
    PA: ["Panama", "巴拿马"],
    PG: ["Papua New Guinea", "巴布亚新几内亚"],
    PY: ["Paraguay", "巴拉圭"],
    PE: ["Peru", "秘鲁"],
    PN: ["Pitcairn Islands", "皮特凯恩群岛"],
    PL: ["Poland", "波兰"],
    PT: ["Portugal", "葡萄牙"],
    PR: ["Puerto Rico", "波多黎各"],
    QA: ["Qatar", "卡塔尔"],
    MK: ["Republic of Macedonia (FYROM)", "马其顿"],
    CG: ["Republic of the Congo", "刚果（布）"],
    RE: ["Réunion", "留尼汪"],
    RO: ["Romania", "罗马尼亚"],
    RU: ["Russian Federation", "俄罗斯"],
    RW: ["Rwanda", "卢旺达"],
    BL: ["Saint Barthélemy", "圣巴泰勒米岛"],
    MF: ["Saint Martin (France)", "法属圣马丁"],
    PM: ["Saint-Pierre and Miquelon", "圣皮埃尔和密克隆"],
    WS: ["Samoa", "萨摩亚"],
    SM: ["San Marino", "圣马力诺"],
    ST: ["Sao Tome & Principe", "圣多美和普林西比"],
    SA: ["Saudi Arabia", "沙特阿拉伯"],
    SN: ["Senegal", "塞内加尔"],
    RS: ["Serbia", "塞尔维亚"],
    SC: ["Seychelles", "塞舌尔"],
    SL: ["Sierra Leone", "塞拉利昂"],
    SG: ["Singapore", "新加坡"],
    SX: ["Sint Maarten", "荷属圣马丁"],
    SK: ["Slovakia", "斯洛伐克"],
    SI: ["Slovenia", "斯洛文尼亚"],
    SB: ["Solomon Islands", "所罗门群岛"],
    SO: ["Somalia", "索马里"],
    ZA: ["South Africa", "南非"],
    GS: ["South Georgia and the South Sandwich Islands", "南乔治亚岛和南桑威奇群岛"],
    KR: ["South Korea", "韩国"],
    SS: ["South Sudan", "南苏丹"],
    ES: ["Spain", "西班牙"],
    LK: ["Sri Lanka", "斯里兰卡"],
    SH: ["St. Helena & Dependencies", "圣赫勒拿"],
    KN: ["St. Kitts & Nevis", "圣基茨和尼维斯"],
    LC: ["St. Lucia", "圣卢西亚"],
    VC: ["St. Vincent & the Grenadines", "圣文森特和格林纳丁斯"],
    SD: ["Sudan", "苏丹"],
    SR: ["Suriname", "苏里南"],
    SJ: ["Svalbard and Jan Mayen", "斯瓦尔巴群岛和扬马延岛"],
    SZ: ["Swaziland", "斯威士兰"],
    SE: ["Sweden", "瑞典"],
    CH: ["Switzerland", "瑞士"],
    SY: ["Syria", "叙利亚"],
    TW: ["Taiwan", "中国台湾"],
    TJ: ["Tajikistan", "塔吉克斯坦"],
    TZ: ["Tanzania", "坦桑尼亚"],
    TH: ["Thailand", "泰国"],
    BS: ["The Bahamas", "巴哈马"],
    KM: ["The Comoros", "科摩罗"],
    PH: ["The Philippines", "菲律宾"],
    TL: ["Timor-Leste (East Timor)", "东帝汶"],
    TG: ["Togo", "多哥"],
    TK: ["Tokelau", "托克劳"],
    TO: ["Tonga", "汤加"],
    TT: ["Trinidad & Tobago", "特立尼达和多巴哥"],
    TN: ["Tunisia", "突尼斯"],
    TR: ["Turkey", "土耳其"],
    TM: ["Turkmenistan", "土库曼斯坦"],
    TC: ["Turks & Caicos Islands", "特克斯和凯科斯群岛"],
    TV: ["Tuvalu", "图瓦卢"],
    UG: ["Uganda", "乌干达"],
    UA: ["Ukraine", "乌克兰"],
    AE: ["United Arab Emirates", "阿联酋"],
    UM: ["United States Minor Outlying Islands", "美国本土外小岛屿"],
    US: ["United States", "美国"],
    VI: ["United States Virgin Islands", "美属维尔京群岛"],
    UY: ["Uruguay", "乌拉圭"],
    UZ: ["Uzbekistan", "乌兹别克斯坦"],
    VU: ["Vanuatu", "瓦努阿图"],
    VA: ["Vatican City (The Holy See)", "梵蒂冈"],
    VE: ["Venezuela", "委内瑞拉"],
    VN: ["Vietnam", "越南"],
    WF: ["Wallis and Futuna", "瓦利斯和富图纳"],
    EH: ["Western Sahara", "西撒哈拉"],
    YE: ["Yemen", "也门"],
    ZM: ["Zambia", "赞比亚"],
    ZW: ["Zimbabwe", "津巴布韦"]
};
